name: Daily Data Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Fetch data from API
        run: |
          SCRIPT_ID="YOUR_SCRIPT_ID"
          curl -o data.json "https://script.google.com/macros/s/${SCRIPT_ID}/exec"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Daily data update"
          git push
